/**
 * Microsoft Fluent 3D emoji (MIT licence, © Microsoft Corporation), self-hosted as
 * 160px WebP in public/emoji/. scripts/fetch-emoji.mjs reads this list with a regex,
 * so keep each entry on ONE line in the form ['name', 'Fluent folder', skinToneVariant].
 */
export const EMOJI_SOURCES = [
	// Baby, family, celebration
	['baby', 'Baby', true],
	['baby-bottle', 'Baby bottle', false],
	['teddy-bear', 'Teddy bear', false],
	['ribbon', 'Ribbon', false],
	['balloon', 'Balloon', false],
	['party-popper', 'Party popper', false],
	['wrapped-gift', 'Wrapped gift', false],
	['hatching-chick', 'Hatching chick', false],
	['hugging-face', 'Hugging face', false],
	['waving-hand', 'Waving hand', true],
	['love-letter', 'Love letter', false],
	['folded-hands', 'Folded hands', true],
	// Sky and sparkle
	['sparkles', 'Sparkles', false],
	['star', 'Star', false],
	['glowing-star', 'Glowing star', false],
	['cloud', 'Cloud', false],
	['crescent-moon', 'Crescent moon', false],
	// Hearts
	['red-heart', 'Red heart', false],
	['pink-heart', 'Pink heart', false],
	['blue-heart', 'Blue heart', false],
	['two-hearts', 'Two hearts', false],
	// Faces and polls
	['thinking-face', 'Thinking face', false],
	['eyes', 'Eyes', false],
	['nose', 'Nose', true],
	['person-curly-hair', 'Person curly hair', true],
	['smiling-face-with-smiling-eyes', 'Smiling face with smiling eyes', false],
	['sleeping-face', 'Sleeping face', false],
	['loudly-crying-face', 'Loudly crying face', false],
	['face-with-tears-of-joy', 'Face with tears of joy', false],
	['face-holding-back-tears', 'Face holding back tears', false],
	['melting-face', 'Melting face', false],
	['dna', 'Dna', false],
	['magnifying-glass', 'Magnifying glass tilted left', false],
	// Objects
	['light-bulb', 'Light bulb', false],
	['game-die', 'Game die', false],
	['tear-off-calendar', 'Tear-off calendar', false],
	['bullseye', 'Bullseye', false],
	['crown', 'Crown', false],
	['open-book', 'Open book', false],
	['key', 'Key', false],
	['gem-stone', 'Gem stone', false],
	['newspaper', 'Newspaper', false],
	['soccer-ball', 'Soccer ball', false],
	['musical-notes', 'Musical notes', false],
	['clapper-board', 'Clapper board', false],
	['birthday-cake', 'Birthday cake', false],
	['sun-behind-small-cloud', 'Sun behind small cloud', false],
	['memo', 'Memo', false],
	// Fruit of the week
	['seedling', 'Seedling', false],
	['herb', 'Herb', false],
	['green-heart', 'Green heart', false],
	['blueberries', 'Blueberries', false],
	['beans', 'Beans', false],
	['grapes', 'Grapes', false],
	['tangerine', 'Tangerine', false],
	['fallen-leaf', 'Fallen leaf', false],
	['lemon', 'Lemon', false],
	['peach', 'Peach', false],
	['red-apple', 'Red apple', false],
	['avocado', 'Avocado', false],
	['pear', 'Pear', false],
	['bell-pepper', 'Bell pepper', false],
	['mango', 'Mango', false],
	['banana', 'Banana', false],
	['carrot', 'Carrot', false],
	['melon', 'Melon', false],
	['ear-of-corn', 'Ear of corn', false],
	['broccoli', 'Broccoli', false],
	['potato', 'Potato', false],
	['eggplant', 'Eggplant', false],
	['jack-o-lantern', 'Jack-o-lantern', false],
	['leafy-green', 'Leafy green', false],
	['coconut', 'Coconut', false],
	['pineapple', 'Pineapple', false],
	['watermelon', 'Watermelon', false],
] as const;

export type EmojiName = (typeof EMOJI_SOURCES)[number][0];

export const emojiSrc = (name: EmojiName): string => `/emoji/${name}.webp`;
